version: '3.7'

services:

  database:
    container_name: DataBase_PostgreSQL
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: airport_management
    user: root
    volumes:
      - db_volume:/var/lib/postgresql/
    networks:
      - default_network
    ports:
      - 5432:5432

  adminer:
    container_name: DataBase_Adminer
    image: adminer:latest
    ports:
      - 8080:8081
    networks:
      - default_network
    depends_on:
      - database

  zookeeper:
    container_name: Zookeeper_Server
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - default_network
    ports:
      - 2181:2181
    volumes:
      - zookeeper_volume:/data

  kafka:
    container_name: Kafka_Server
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_KAFKA://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_KAFKA:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    hostname: kafka
    volumes:
      - kafka_volume:/bitnami
    networks:
      - default_network
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

  kafdrop:
    container_name: Kafka_Manager
    image: obsidiandynamics/kafdrop:latest
    networks:
      - default_network
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
    depends_on:
      - kafka

networks:
  default_network:
    driver: bridge

volumes:
  zookeeper_volume:
    name: zookeeper_volume
    driver: local
  kafka_volume:
    name: kafka_volume
    driver: local
  db_volume:
    name: db_volume
    driver: local
