version: '3.7'

services:

  database:
    container_name: DataBase_PostgreSQL
    image: postgres:latest
    #restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: airport_management
    user: root
    volumes:
      # host_path:container_path
      - db_volume:/var/lib/postgresql/
    networks:
      - default_network
    ports:
      - 5432:5432

  adminer:
    container_name: DataBase_Adminer
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - default_network

networks:
  default_network:
    driver: bridge

volumes:
  db_volume:
    name: db_volume
